name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # This pattern matches your version tags

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/nicolashaas/golang-kanban
          # Generate tags based on:
          # - semver tag (e.g., v1.2.3) when present
          # - branch name for branch events
          # - commit SHA as a fallback
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64 #,linux/arm64 action takes too long, enable later
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
